jService-master-1/config/routes.rb
JArchive::Application.routes.draw do

  get "search" => "search#index"
  get "search/:query" => "search#index", :as => "search_term"

  get "popular" => "popular#index"
  get "popular/:category_id" => "popular#list", :as => "popular_list"
  get "api/random" => "api#random",  defaults: {format: :json}
  get "api/final" => "api#final",  defaults: {format: :json}
  get "api/clues" => "api#clues", defaults: {format: :json}
  get "api/categories" => "api#categories", defaults: {format: :json}
  get "api/category" => "api#single_category", defaults: {format: :json}
  post "api/invalid" => "api#mark_invalid", defaults: {format: :json}

  get "index/home", :as => "home"
  get "index/about"
  resources :game_ids

  resources :categories

  resources :clues

  root :to => 'index#home'

end

jService-master-1/app/models/clue.rb
class Clue < ActiveRecord::Base
  
  belongs_to :category, :counter_cache => true

  def to_json(options={})
     options[:except] ||= [:updated_at, :created_at]
     super(options)
  end
end

jService-master-1/app/controllers/clues_controller.rb
class CluesController < ApplicationController
  # GET /clues
  # GET /clues.json
  def index
    @clues = Clue.last(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clues }
    end
  end

  # GET /clues/1
  # GET /clues/1.json
  def show
    @clue = Clue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clue }
    end
  end

  # GET /clues/new
  # GET /clues/new.json
  def new
    @clue = Clue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clue }
    end
  end

  # GET /clues/1/edit
  def edit
    @clue = Clue.find(params[:id])
  end

  # POST /clues
  # POST /clues.json
  def create
    @clue = Clue.new(params[:clue])

    respond_to do |format|
      if @clue.save
        format.html { redirect_to @clue, notice: 'Clue was successfully created.' }
        format.json { render json: @clue, status: :created, location: @clue }
      else
        format.html { render action: "new" }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clues/1
  # PUT /clues/1.json
  def update
    @clue = Clue.find(params[:id])

    respond_to do |format|
      if @clue.update_attributes(params[:clue])
        format.html { redirect_to @clue, notice: 'Clue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clues/1
  # DELETE /clues/1.json
  def destroy
    @clue = Clue.find(params[:id])
    @clue.destroy

    respond_to do |format|
      format.html { redirect_to clues_url }
      format.json { head :no_content }
    end
  end
end

jService-master-1/app/helpers/clues_helper.rb
module CluesHelper
end

jService-master-1/app/views/clues/_form.html.erb
<%= form_for @clue, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :answer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :answer, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :question, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :value, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :airdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :airdate, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clues_path, :class => 'btn' %>
  </div>
<% end %>

jService-master-1/app/views/clues/edit.html.erb
<%- model_class = Clue -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

jService-master-1/app/views/clues/index.html.erb
<%- model_class = Clue -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:answer) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:airdate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clues.each do |clue| %>
      <tr>
        <td><%= link_to clue.id, clue_path(clue) %></td>
        <td><%= clue.answer %></td>
        <td><%= clue.question %></td>
        <td><%= clue.value %></td>
        <td><%= clue.category.title %></td>
        <td><%= clue.airdate %></td>
        <td><%=l clue.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_clue_path(clue), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      clue_path(clue),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_clue_path,
            :class => 'btn btn-primary' %>

jService-master-1/app/views/clues/new.html.erb
<%- model_class = Clue -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

jService-master-1/app/views/clues/show.html.erb
<%= render "layouts/menu" %>

<ol class="breadcrumb">
  <li><%= link_to "index" %></li>
</ol>

<%- model_class = Clue -%>

<div class="container">
    <div class="row">
        <div class=" col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @clue.category.title.humanize %> <span class="badge badge-success">$<%= @clue.value %></span></h3>
          </div>
          <div class="panel-body">
            <p><strong>Question:</strong> <%= @clue.question %></p>
              <hr />
            
            <p>
                <strong>Answer: </strong> 
                <a class="btn btn-sm btn-default" id="show-answer">Show</a>
                <span id="answer"><%= @clue.answer.humanize %></span>
            </p>
            <small class="pull-right"><em>Airdate: <%= @clue.airdate.strftime('%b %-d %Y') %></em></small>
          </div>
        </div>
        
</div>
</div>
</div>
</div>